#!/usr/bin/env python
"""Entry point for Django management commands.

This file is the standard `manage.py` generated by Django. It sets up the
`DJANGO_SETTINGS_MODULE` environment variable and delegates to Django's
`execute_from_command_line` to run commands such as `runserver`, `migrate`, and `shell`.

Usage examples (run from project root):
  python manage.py runserver
  python manage.py migrate
  python manage.py createsuperuser
"""

import os
import sys


def main():
    """Configure environment and run the Django command-line utility.

    This function intentionally avoids importing Django until after the
    environment variable is set so that commands like `migrate` work when
    invoked from a fresh virtual environment.
    """
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'quizapp.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        # Friendly error with hints for developers who may not have installed dependencies
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
