"""App-level views placeholder.

This file was generated by Django when the app was created. The project places
the main site views in `quizapp/view.py` instead (top-level app module). Keep
this file minimal, but leave a short explanation for contributors.
"""

from django.shortcuts import render

# Create your views here. See `quizapp/view.py` for the application's primary handlers.
